### ISSUE TITLE
start error,

### ISSUE THREAD

**Issue by eriknyk** [black-screen/black-screen#116]
Hi, 

I'm having the following error on OSX El Capitan:

```
➜  black-screen git:(master) npm start

> black-screen@0.0.1 start /Users/erik/Applications/black-screen
> gulp

[11:37:20] Requiring external module babel-core/register
[11:37:21] Using gulpfile ~/Applications/black-screen/gulpfile.babel.js
[11:37:21] Starting 'default'...
[11:37:21] Starting 'watch'...
[11:37:22] Starting 'clean'...
[11:37:22] Finished 'clean' after 127 ms
[11:37:22] Starting 'typescript'...
[11:37:22] Starting 'sass'...
[11:37:22] Starting 'react'...
[11:37:22] Finished 'default' after 956 ms
[11:37:23] gulp-notify: [Black Screen Watcher] React has been compiled.
[11:37:23] Finished 'react' after 1.29 s
[11:37:27] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[11:37:27] Finished 'typescript' after 4.99 s
[11:37:28] /Users/erik/Applications/black-screen/compiled/all.css reloaded.
[11:37:28] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[11:37:28] Finished 'sass' after 6.47 s
[11:37:28] Finished 'watch' after 7.06 s
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/erik/Applications/black-screen/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/Users/erik/Applications/black-screen/node_modules/electron-prebuilt/index.js:4:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command `PATH=node_modules/.bin:$PATH electron .` failed with exit code 1

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erik/Applications/black-screen/npm-debug.log
```

**Comment by mzgnr** [comment]
can you look at this issue first ? https://github.com/black-screen/black-screen/issues/90

**Comment by shockone** [comment]
@eriknyk, I saw this error before. Please remove the `node_modules` directory and install the modules again. It should help, but if it doesn't, please reopen the issue.

**Comment by RobertoUa** [comment]
I had the same issue. `rm -rf node_modules && npm install` fixed it.
