### ISSUE TITLE
Black Screen doesn't do anything. Can't find ptyw.js

### ISSUE THREAD

**Issue by hdavidzhu** [black-screen/black-screen#147]
```
"Uncaught Error: Cannot find module 'ptyw.js'", source: module.js (338)
```

Bug achieved by going through the installation steps:
```
git clone https://github.com/black-screen/black-screen
cd black-screen
npm install
npm run package
ls
npm start
```

![screen shot 2015-09-21 at 5 02 07 pm](https://cloud.githubusercontent.com/assets/3756871/10004967/837e2a28-6082-11e5-8ac4-42ceb6cc6548.png)

![screen shot 2015-09-21 at 5 02 25 pm](https://cloud.githubusercontent.com/assets/3756871/10004988/96c01ce0-6082-11e5-9ff4-828521a46696.png)

**Comment by mzgnr** [comment]
are you using node v4 ?

**Comment by iiegor** [comment]
@mzgnr black-screen should work with node v4. The problem is that the node module 'ptyw.js' wasn't installed/compiled correctly. Try running ``npm install ptyw.js``.

**Comment by hdavidzhu** [comment]
```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/hdavidzhu/.node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/hdavidzhu/.node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hdavidzhu/black-screen/node_modules/ptyw.js
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/hdavidzhu/.node/bin/npm" "install" "ptyw.js"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ptyw.js@0.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.
```

**Comment by vikas17a** [comment]
@hdavidzhu check if you have install gyp it may be conflicting with node-gyp for me ``apt-get remove gyp`` worked

**Comment by hdavidzhu** [comment]
@vikas17a I'm in OSX. Would this be how you do it? It's not working either.

```
➜  ~  brew remove gyp
Error: No such keg: /usr/local/Cellar/gyp
➜  ~  brew remove node-gyp
Error: No such keg: /usr/local/Cellar/node-gyp
➜  ~
```

**Comment by shockone** [comment]
This one should help:
```bash
rm -r ~/.node-gyp
npm install
```

**Comment by hdavidzhu** [comment]
@shockone that worked! Thanks.
