### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by adrian-budau** [black-screen/black-screen#150]
So I've tried searching for a solution, I just can't seem to find one.

It seems to fail to install fsevents 1.0.0 and fail at node-pre-gyp.

I've tried to manually install fsevents and it worked smoothly so it does not seem to be a problem of fsevents.

I'm on a MacBookPro Retina 2014, OS X Yosemite, XCode 7 and Nodejs 4.1.1. I've tried with iojs 3.0.0 and get the same thing.

```
> black-screen@0.0.1 preinstall /Users/adrianbudau/work/black-screen
> npm prune

unbuild fsevents@1.0.0
npm WARN package.json react-json-inspector@5.2.1 scripts['server'] should probably be scripts['start'].

> black-screen@0.0.1 postinstall /Users/adrianbudau/work/black-screen
> bower prune; bower install; electron-rebuild


> ptyw.js@0.3.2 install /Users/adrianbudau/work/black-screen/node_modules/ptyw.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> nslog@3.0.0 install /Users/adrianbudau/work/black-screen/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node

> fsevents@1.0.0 install /Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.33.0

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 0.33.0
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:444:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:462:10)
node-pre-gyp ERR! stack     at Module.load (module.js:339:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:294:12)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/adrianbudau/work/black-screen/node_modules/babel/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v1.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/adrianbudau/work/black-screen/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.33.0" "--arch=x64"
npm ERR! node v1.4.3
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adrianbudau/work/black-screen/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/adrianbudau/work/black-screen/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Socket.<anonymous> (child_process.js:1153:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/adrianbudau/.nvm/versions/io.js/v1.4.3/bin/iojs" "/Users/adrianbudau/.nvm/versions/io.js/v1.4.3/bin/npm" "install"
npm ERR! node v1.4.3
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 postinstall: `bower prune; bower install; electron-rebuild`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 postinstall script 'bower prune; bower install; electron-rebuild'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower prune; bower install; electron-rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adrianbudau/work/black-screen/npm-debug.log
```

**Comment by tianyutingxy** [comment]
I got the same error.

**Comment by shockone** [comment]
Fixed in the latest master. Thank you for reporting.
