### ISSUE TITLE
compile-tests error

### ISSUE THREAD

**Issue by aflyax** [black-screen/black-screen#179]
```
sudo npm run test

> black-screen@0.0.1 test /Users/aflyax/Documents/git/black-screen
> gulp typescript; gulp compile-tests; electron run-tests.js

[00:00:02] Requiring external module babel-core/register
[00:00:03] Using gulpfile ~/Documents/git/black-screen/gulpfile.babel.js
[00:00:03] Starting 'typescript'...
[00:00:06] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[00:00:06] Finished 'typescript' after 3.38 s
[00:00:06] Requiring external module babel-core/register
[00:00:07] Using gulpfile ~/Documents/git/black-screen/gulpfile.babel.js
[00:00:07] Starting 'compile-tests'...
test/src/history_test.ts(1,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/mocha/mocha.d.ts' not found.
test/src/history_test.ts(2,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/chai/chai.d.ts' not found.
test/src/history_test.ts(5,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/history_test.ts(5,23): error TS2307: Cannot find module 'chai'.
test/src/history_test.ts(6,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/history_test.ts(9,1): error TS2304: Cannot find name 'describe'.
test/src/history_test.ts(11,5): error TS2304: Cannot find name 'afterEach'.
test/src/history_test.ts(11,31): error TS2339: Property 'clear' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(13,5): error TS2304: Cannot find name 'describe'.
test/src/history_test.ts(14,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(15,28): error TS2339: Property 'size' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(18,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(19,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(20,28): error TS2339: Property 'size' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(22,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(23,28): error TS2339: Property 'size' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(27,5): error TS2304: Cannot find name 'describe'.
test/src/history_test.ts(28,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(29,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(30,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(32,28): error TS2339: Property 'size' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(35,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(36,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(37,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(38,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(40,28): error TS2339: Property 'size' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(44,5): error TS2304: Cannot find name 'describe'.
test/src/history_test.ts(45,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(46,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(47,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(49,28): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(50,28): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(53,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(54,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(56,28): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(57,28): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(61,5): error TS2304: Cannot find name 'describe'.
test/src/history_test.ts(62,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(63,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(64,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(66,21): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(67,21): error TS2339: Property 'getPrevious' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(68,28): error TS2339: Property 'getNext' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(71,9): error TS2304: Cannot find name 'it'.
test/src/history_test.ts(72,21): error TS2339: Property 'append' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/history_test.ts(74,35): error TS2339: Property 'getNext' does not exist on type 'typeof "/Users/aflyax/Documents/git/black-screen/src/History"'.
test/src/providers/file_test.ts(1,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/mocha/mocha.d.ts' not found.
test/src/providers/file_test.ts(2,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/chai/chai.d.ts' not found.
test/src/providers/file_test.ts(5,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/file_test.ts(5,23): error TS2307: Cannot find module 'chai'.
test/src/providers/file_test.ts(6,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/file_test.ts(7,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/file_test.ts(8,9): error TS2305: Module '"/Users/aflyax/Documents/git/black-screen/src/Interfaces"' has no exported member 'Suggestion'.
test/src/providers/file_test.ts(9,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/file_test.ts(14,1): error TS2304: Cannot find name 'describe'.
test/src/providers/file_test.ts(15,5): error TS2304: Cannot find name 'describe'.
test/src/providers/file_test.ts(16,9): error TS2304: Cannot find name 'it'.
test/src/providers/file_test.ts(16,50): error TS7006: Parameter 'done' implicitly has an 'any' type.
test/src/providers/file_test.ts(17,30): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
test/src/providers/file_test.ts(20,13): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
test/src/providers/file_test.ts(20,69): error TS7006: Parameter 'results' implicitly has an 'any' type.
test/src/providers/file_test.ts(26,9): error TS2304: Cannot find name 'it'.
test/src/providers/file_test.ts(26,46): error TS7006: Parameter 'done' implicitly has an 'any' type.
test/src/providers/file_test.ts(27,30): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
test/src/providers/file_test.ts(30,13): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
test/src/providers/invocation_test.ts(1,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/mocha/mocha.d.ts' not found.
test/src/providers/invocation_test.ts(2,1): error TS6053: File '/Users/aflyax/Documents/git/black-screen/dts/typings/chai/chai.d.ts' not found.
test/src/providers/invocation_test.ts(5,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/invocation_test.ts(5,23): error TS2307: Cannot find module 'chai'.
test/src/providers/invocation_test.ts(6,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.
test/src/providers/invocation_test.ts(11,1): error TS2304: Cannot find name 'describe'.
test/src/providers/invocation_test.ts(12,5): error TS2304: Cannot find name 'describe'.
test/src/providers/invocation_test.ts(13,9): error TS2304: Cannot find name 'it'.
test/src/providers/invocation_test.ts(13,60): error TS7006: Parameter 'done' implicitly has an 'any' type.
test/src/providers/invocation_test.ts(14,30): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
[00:00:09] TypeScript: 75 semantic errors
[00:00:09] TypeScript: emit succeeded (with errors)
[00:00:09] Finished 'compile-tests' after 1.88 s
App threw an error when running [ReferenceError: chai is not defined]
```

Atom says:

```
Uncaught Exception:
ReferenceError: chai is not defined
    at Object.<anonymous> (/Users/aflyax/Documents/git/black-screen/compiled/test/src/history_test.js:4:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/aflyax/Documents/git/black-screen/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/aflyax/Documents/git/black-screen/node_modules/mocha/lib/mocha.js:213:14)
```

**Comment by G07cha** [comment]
Have you installed all dependencies? As I can see `chai` module don't installed when it should be.
Run `npm install` in black-screen folder and try again.

**Comment by shockone** [comment]
Tests don't work, and even if they did, they don't cover anything. It bothers me a lot and we have to do something about them.

**Comment by aflyax** [comment]
```
➜  black-screen git:(master) npm install

> black-screen@0.0.1 preinstall /Users/aflyax/Documents/git/black-screen
> npm prune

 
> nslog@3.0.0 install /Users/aflyax/Documents/git/black-screen/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node

> ptyw.js@0.3.4 install /Users/aflyax/Documents/git/black-screen/node_modules/ptyw.js
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> black-screen@0.0.1 postinstall /Users/aflyax/Documents/git/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /Users/aflyax/Documents/git/black-screen
> HOME=~/.electron-gyp cd node_modules/ptyw.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
electron-rebuild@1.0.2 node_modules/electron-rebuild
├── ncp@2.0.0
├── promise@7.0.4 (asap@2.0.3)
├── rimraf@2.4.4 (glob@5.0.15)
├── yargs@3.30.0 (camelcase@1.2.1, decamelize@1.1.1, window-size@0.1.4, y18n@3.2.0, os-locale@1.4.0, cliui@3.0.3)
├── babel-runtime@5.8.34 (core-js@1.2.6)
├── nslog@3.0.0 (nan@2.1.0)
└── npm@2.14.12

ptyw.js@0.3.4 node_modules/ptyw.js
├── extend@1.2.1
└── nan@2.0.5
```

**Comment by aflyax** [comment]
Trying to install xcode now, will see if that helps.

**Comment by aflyax** [comment]
Installed XCode. Now:

```
➜  black-screen git:(master) npm install         

> black-screen@0.0.1 preinstall /Users/aflyax/Documents/git/black-screen
> npm prune


> black-screen@0.0.1 postinstall /Users/aflyax/Documents/git/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /Users/aflyax/Documents/git/black-screen
> HOME=~/.electron-gyp cd node_modules/ptyw.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
➜  black-screen git:(master) npm run package 

> black-screen@0.0.1 package /Users/aflyax/Documents/git/black-screen
> gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns'

[11:55:38] Requiring external module babel-core/register
[11:55:39] Using gulpfile ~/Documents/git/black-screen/gulpfile.babel.js
[11:55:39] Starting 'typescript'...
[11:55:39] Starting 'sass'...
[11:55:39] 'sass' errored after 30 ms
[11:55:39] Error: The `libsass` binding was not found in /Users/aflyax/Documents/git/black-screen/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/aflyax/Documents/git/black-screen/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/aflyax/Documents/git/black-screen/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/aflyax/Documents/git/black-screen/node_modules/babel-core/node_modules/babel-register/lib/node.js:135:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/aflyax/Documents/git/black-screen/node_modules/gulp-sass/index.js:176:21)
[11:55:42] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[11:55:42] Finished 'typescript' after 3.09 s

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "package"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 package: `gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 package script 'gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns''.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns'
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aflyax/Documents/git/black-screen/npm-debug.log
```

**Comment by aflyax** [comment]
`npm rebuild node-sass` and rebuilding worked. Starts now.
