### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by sergiovilar** [black-screen/black-screen#90]
Hello, I'm trying to install using the `npm install` command and I get this error:

```
> pty.js@0.3.0 install /Users/sergiovilar/repos/black-screen/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/pty.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sergiovilar/repos/black-screen/node_modules/pty.js
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

I'm running El Capitan and I have the xcode tools installed.

**Comment by joshtoo** [comment]
@sergiovilar -lgxx_s10.5 is an issue with the xcode command line tools and something I am currently troubleshooting. Could you please update this issue with the xcode version you are using currently?

**Comment by sergiovilar** [comment]
@joshtoo sure!

I'm using Xcode 7.0 beta 6 (7A192o) installed in `/Applications/Xcode.app/Contents/Developer`.
My gcc version is:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by joshtoo** [comment]
You have a mismatch between your xcode version and the underlying clang version.

"Apple LLVM version 6.1.0" is xcode 6.4

Open the Xcode Beta.app and go to the Locations tab.

<img width="739" alt="screen shot 2015-09-08 at 3 09 36 pm" src="https://cloud.githubusercontent.com/assets/8420490/9746134/bd17f8dc-563b-11e5-889b-b97659ec0737.png">

Change command line tools to Xcode 7.0 (something) and rebuild with the latest version of master.

**Comment by fibric** [comment]
check #27

**Comment by sergiovilar** [comment]
That's right, is working now.

Thank you!

**Comment by jesusjjf** [comment]
I'm having the similar error

```
> pty.js@0.3.0 install /path-to/black-screen/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

2015-09-11 14:31:54.107 xcodebuild[27585:1105323] [MT] PluginLoading: Required plug-in compatibility UUID CC0D0F4F-05B3-431A-8F33-F84AFCB2C651 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
clang: error: no such file or directory: '/path-to/black-screen/node_modules/electron-rebuild/lib/headers/.node-gyp/0.31.2/src'
clang: error: no such file or directory: '/path-to/black-screen/node_modules/electron-rebuild/lib/headers/.node-gyp/0.31.2/deps/uv/include'
clang: error: no such file or directory: '/path-to/black-screen/node_modules/electron-rebuild/lib/headers/.node-gyp/0.31.2/deps/v8/include'
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/path-to/black-screen/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/username/.nvm/versions/node/v4.0.0/bin/node" "/path-to/black-screen/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path-to/black-screen/node_modules/pty.js
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/username/.nvm/versions/node/v4.0.0/bin/node" "/path-to/black-screen/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.31.2" "--arch=x64"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path-to/black-screen/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/path-to/black-screen/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

some additional information:

`clang --version`
```
Apple LLVM version 7.0.0 (clang-700.1.74)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
xcode command line tools:
![screen shot 2015-09-11 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/2798097/9826952/cca7328c-5892-11e5-9bfc-d318520da05e.png)
